version: '3.9'

networks:
  app-network-public:
    driver: bridge

volumes:
  sqlvolume:

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-CU11-ubuntu-22.04
    container_name: db-sqlserver2022
    networks:
      - app-network-public
    restart: always
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=P@ssw0rd!
    ports:
      - '1433:1433'
    volumes:
      - sqlvolume:/var/opt/mssql